# Generated by Django 5.1.15 on 2026-09-23 12:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='点检项')),
                ('standard', models.CharField(blank=True, max_length=200, verbose_name='标准值/说明')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '点检项',
                'verbose_name_plural': '点检项',
                'ordering': ['equipment', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CheckRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector', models.CharField(blank=True, max_length=50, verbose_name='点检人')),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='点检时间')),
                ('has_abnormal', models.BooleanField(default=False, verbose_name='存在异常')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '点检记录',
                'verbose_name_plural': '点检记录',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='设备编号')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('workshop', models.CharField(db_index=True, max_length=50, verbose_name='所在车间')),
                ('cycle_days', models.PositiveIntegerField(default=1, verbose_name='点检周期(天)')),
                ('owner', models.CharField(blank=True, max_length=50, verbose_name='负责人')),
                ('qr_token', models.CharField(editable=False, max_length=32, unique=True, verbose_name='二维码token')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['workshop', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('normal', '正常'), ('abnormal', '异常')], default='normal', max_length=10, verbose_name='结果')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='异常描述')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='board.checkitem', verbose_name='点检项')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='board.checkrecord', verbose_name='点检记录')),
            ],
            options={
                'verbose_name': '点检结果',
                'verbose_name_plural': '点检结果',
            },
        ),
        migrations.AddField(
            model_name='checkrecord',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='board.equipment', verbose_name='设备'),
        ),
        migrations.AddField(
            model_name='checkitem',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='board.equipment', verbose_name='设备'),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=32, unique=True, verbose_name='工单编号')),
                ('title', models.CharField(max_length=200, verbose_name='故障/工单标题')),
                ('description', models.TextField(blank=True, verbose_name='详情')),
                ('assignee', models.CharField(blank=True, max_length=50, verbose_name='指派给')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('done', '已完成')], db_index=True, default='pending', max_length=12, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='board.equipment', verbose_name='设备')),
                ('source_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='board.checkresult', verbose_name='来源异常项')),
            ],
            options={
                'verbose_name': '维修工单',
                'verbose_name_plural': '维修工单',
                'ordering': ['-created_at'],
            },
        ),
    ]
