# Generated by Django 5.1.15 on 2026-09-23 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模板名称')),
                ('category', models.CharField(blank=True, help_text='如 注塑机 / 空压机(仅作分类提示)', max_length=50, verbose_name='适用设备类型')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '点检标准模板',
                'verbose_name_plural': '点检标准模板',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CheckTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='点检项')),
                ('standard', models.CharField(blank=True, max_length=200, verbose_name='标准值/说明')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='board.checktemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '模板点检项',
                'verbose_name_plural': '模板点检项',
                'ordering': ['template', 'order', 'id'],
            },
        ),
    ]
